version: '3'

services: 

  mariadb:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./filerun/db:/var/lib/mysql

  webfilerun:
    image: afian/filerun
    environment:
      FR_DB_HOST: mariadb
      FR_DB_PORT: 3306
      FR_DB_NAME: ${MYSQL_DATABASE}
      FR_DB_USER: ${MYSQL_USER}
      FR_DB_PASS: ${MYSQL_ROOT_PASSWORD}
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - mariadb
    links:
      - mariadb:mariadb
    ports:
      - "5080:80"
    volumes:
      - ./filerun/html:/var/www/html
      - ./filerun/user-files:/user-files

  tomcat:
    image: tomcat:9-slim
    volumes: 
      - ./filerun/user-files:/usr/local/tomcat/webapps/static
    depends_on:
      - webfilerun
    ports:
      - "9080:8080"
